### ISSUE TITLE
見積もり画面で、保存されている見積りでも、「契約画面へいく」ボタンが押せない

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/kokoas#125]
**Describe the bug**
下記の時、「契約画面へいく」ボタンが無効になっている。
(保存されていない変更があります　のメッセージが表示されている)
・既存の見積りを選択して開いたとき
・新規作成した見積もりを初めて保存したとき

**To Reproduce**
見積もり画面で、工事情報を入力したあと、以下の行動をとる

1. 「見積りを選択する」ボタンをクリックして既存の見積りを選択する
2. 新規作成状態のまま見積もりを作成し、保存ボタンを押した直後

**Expected behavior**
確認中

**Comment by Lorenzras** [comment]
動作：

新規の場合、
無効状態で、HelperText = "保存してください"

編集の場合、
最初状態は有効。
フォーム触ったら、保存されるまで無効。
