### ISSUE TITLE
formに設定している大項目ごとの小計欄を、objectの配列に修正する

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/kokoas#36]
**Describe the bug**
form内initialValuesに大項目ごとの小計を設定しているが、
要素数が可変のため、itemsと同様、object型の配列に修正する。

**To Reproduce**
表示用のテーブルも未実装のため、表示含めまだ再現しません

**Expected behavior**
部材の大項目ごとに、金額欄の小計を算出し、formに格納します

**others**
form定義をしたのち、大きく分けて以下2つの対応も必要になる見込みです。
- FormProjEstimateへ、大項目ごとの小計欄(テーブル)表示用の処理追加
- 大項目ごとに小計を算出して、表示とformへ反映する処理

**Comment by Lorenzras** [comment]
計算して表示だけなら、formのステートに格納しなくても、いいかもしれません。

"アプリケーションが必要としている最小限の状態を把握しておき、他に必要なものが出てきたら、そのとき計算すればよいのです"

https://ja.reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state

**Comment by RPA02coco** [comment]
formには最小限の情報を格納する方針とし、本issueは対応不要とします。
