### ISSUE TITLE
数値入力用コンポーネントのformへ登録する型をstringからnumberへ修正する

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/kokoas#37]
**Describe the bug**
INPUTをformに格納する際、number型への型変換がされず、string型で格納されてしまっている

**To Reproduce**
見積もり画面で、単価・数量・利益率を入力すると、formにはstring型で格納されている
なお、form格納値はコンソールで確認している

**Expected behavior**
setValueで格納する際に型変換を行います

**Comment by Lorenzras** [comment]
ありがとうございます。

まだベースのブランチにマージしていないものなので、そのままPRで解決をしましょう。

マージ後、保護されているブランチにバグを見つかったら、Issueをお願いします。

さっそく #25  でコミットを入れましたので、 当IssueをCloseをさせて頂きます。

**Comment by RPA02coco** [comment]
Yupのバリデーションで対応することとし、
FormikInput.tsxでは処置しない方針となりました。
そのため、本件は対応不要とします。
