### ISSUE TITLE
工事種別をデータのラベルが変更されたら、見積もり画面で参照するとエラーが出る。

### ISSUE THREAD

**Issue by Lorenzras** [Lorenzras/kokoas#79]
**Describe the bug**
工事種別をデータのラベルが変更されたら、見積もり画面で参照するとエラーが出る。

**To Reproduce**
1. 工事種別アプリでラベルを変える https://rdmuhwtt6gx7.cybozu.com/k/190/
2. 見積もり画面へ行く。
3. １に参照している工事を選択する。

**Expected behavior**

- 工事種別に変更があった場合、エラー無しで、最新工事種別の状態を取得出来る。

**Screenshots**

![image](https://user-images.githubusercontent.com/2501255/190548488-34b0c4e3-bc70-442c-9f3c-e7ec89a12508.png)

**Comment by RPA02coco** [comment]
PR#84での解消を確認しました。
