### ISSUE TITLE
他のページから見積もり画面に遷移するときに、工事と見積りを設定した状態で開く

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/kokoas#88]
**Describe the bug**
契約画面等から見積もり画面へ移動する際、参照している工事情報に紐づけた状態でページを開けていない

**To Reproduce**

 - 契約を見るのページで、工事情報を検索
 - 見積もりリストから、「見積登録」もしくは「見積作成」ボタンをクリックする
 - 見積りページに遷移する

**Expected behavior**

 - 見積もり画面に既存の見積りを選択するフィールドを設定する
 - useNavigateの引数を修正する

**Comment by Lorenzras** [comment]
#103 に緊急修正を入れましたので、本Issue閉じさせて頂きます。もし、当Issueが解決出来なかったら、再開をお願いします。
